#pragma once

typedef int error_t;
enum Error : error_t {
    // IDENTIFIER
    INVALID_IDENTIFIER =       0x0100,
    INVALID_IDENTIFIER_START = 0x0101,

    // PARSE TYPE
    INVALID_SIZE_QUALIFIER = 0x0200,
    INVALID_SIGN_QUALIFIER = 0x0201,
    UNEXPECTED_TYPE_TOKEN  = 0x0202,
    INVALID_TYPENAME       = 0x0203,
    INVALID_VARIABLE_DECL  = 0x0204,
    NOT_VARIABLE_DECL      = 0x0205,

    // INTERPRETER
    INVALID_LINE = 0x0300,


    // OK
    OK = 0x0
};
